com.js.cool
willin/js.cool pull request #123
Opened 2022-08-06 15:48 UTC by cnzc

- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

用作个人博客和网页

2022-08-06 17:02 UTC, willin requested changes
你这个域名我很难给你通过啊。。。

2022-08-07 11:19 UTC, cnzc commented
好吧，这个域名的确有点刁钻，是我的错。我刚刚重新改了一个正常一点的。感谢指教！

2022-08-07 15:33 UTC, willin commented
你没有网名或者啥常用名有标志性的吗

2022-08-07 15:39 UTC, willin approved these changes

2022-08-07 15:39 UTC, merged

2022-08-08 10:49 UTC, cnzc commented
哎。。。不怎么会起名字啊。