Update active_ns.js
willin/js.cool pull request #232
Opened 2023-02-01 07:06 UTC by lpcra

- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

2023-02-01 11:15 UTC, willin requested changes
Spam?

2023-02-01 11:26 UTC, lpcra commented
您好王老师我是想申请一个域名做业余无线电和网络（类似物联网，工业控制相关）相关的活动但现在还没有真正的项目，但已经有方向了希望通过！

2023-02-01 12:20 UTC, willin commented
do u have another major account?

你是否有其他 Github 大号

2023-02-01 12:38 UTC, lpcra commented
> 您有其他主要客户吗？
> 
> 你是否有其他 Github 大号

没有其他大号，我这个号注册了好几年了，我知道免费资源有多么珍贵

2023-02-02 08:24 UTC, willin approved these changes

2023-02-02 08:24 UTC, merged

2023-02-02 09:19 UTC, lpcra commented
您好有机会的话帮忙添加一下 "ns5.he.net" 吧自动脚本可能失效现在dns只能查询到1到4了，感谢您预祝十五好，