Update active_cname.js
willin/js.cool pull request #301
Opened 2023-04-02 21:41 UTC by gottaegbert

- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

方便国内访问vercel

2023-04-03 02:21 UTC, willin requested changes
invalid format.

2023-04-03 02:21 UTC, willin commented
绑定域名别名不能方便魔法访问。

2023-04-03 18:04 UTC, gottaegbert commented
那请问这个工具有可能方便魔法访问吗？请问是有什么invalid format.

2023-04-04 06:09 UTC, willin commented
不提供该问题的讨论。。。

2023-04-04 06:10 UTC, willin commented
如果您想要个域名别名，修改成正确格式提交。但无法达到你所预期的效果可能。

2023-04-04 18:55 UTC, closed without merging